name: Generate PDF

on:
  push:
    branches: [master]
    paths: ['**.drawio']

jobs:
  generate-pdf:
    name: Generate PDF
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install draw.io
      run: |
        curl -sLO $(curl --silent https://api.github.com/repos/jgraph/drawio-desktop/releases/latest | jq -r '.assets[] | select(.name | test("^draw.io-.*deb$")) | .browser_download_url')
        sudo apt install ./draw.io-*.deb
        rm ./draw.io-*.deb
    - name: Export PDF
      run: |
        mkdir build
        xvfb-run drawio --export --all-pages --output build .
    - name: Update GitHub Pages
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git checkout gh-pages
        git rm --ignore-unmatch *.pdf
        cp -a build/. .
        git add *.pdf
        git commit -m "based on $GITHUB_SHA"
        git push origin gh-pages
