name: Generate PDF

on:
  push:
    branches: [master]

jobs:
  generate-pdf:
    name: Generate PDF
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install draw.io
      run: snap install drawio
    - name: Export PDF
      run: drawio --export --all-pages .
    - uses: actions/upload-artifact@v2
      with:
        name: PDF
        path: *.pdf
