name: Generate PDF

on:
  push:
    branches: [master]

jobs:
  generate-pdf:
    name: Generate PDF
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install draw.io
      run: |
        curl -sLO https://github.com/jgraph/drawio-desktop/releases/download/v13.6.2/draw.io-amd64-13.6.2.deb
        sudo apt install ./draw.io-*.deb
    - name: Export PDF
      run: drawio --export --all-pages .
    - uses: actions/upload-artifact@v2
      with:
        name: PDF
        path: '*.pdf'
