name: Generate PDF

on:
  push:
    branches: [master]

jobs:
  generate-pdf:
    name: Generate PDF
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install draw.io
      run: |
        curl -sLO $(curl --silent https://api.github.com/repos/jgraph/drawio-desktop/releases/latest | jq -r '.assets[] | select(.name | test("^draw.io-.*deb$")) | .browser_download_url')
        sudo apt install ./draw.io-*.deb
        rm ./draw.io-*.deb
    - name: Export PDF
      run: xvfb-run drawio --export --all-pages .
    - uses: actions/upload-artifact@v2
      with:
        name: PDF
        path: '*.pdf'
