name: Generate PDF

on:
  push:
    branches: [master]

jobs:
  generate-pdf:
    name: Generate PDF
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install draw.io
      run: |
        sudo curl -sL -o /usr/local/bin/drawio https://github.com/jgraph/drawio-desktop/releases/download/v13.6.2/draw.io-x86_64-13.6.2.AppImage
        sudo chmod a+x /usr/local/bin/drawio
    - name: Export PDF
      run: drawio --export --all-pages .
    - uses: actions/upload-artifact@v2
      with:
        name: PDF
        path: '*.pdf'
